### ISSUE TITLE
I can set color for all the text of a chunk

### ISSUE THREAD

**Issue by Duvancho321** [kbodwin/flair#11]
{python py, include=FALSE }

```{python py, include=FALSE }
import numpy as np
np.arange(1,100)
```
{r}

```{r}
decorate_chunk("py") %>% 
  flair(   [all text]   , color="orange" )
```

I would like all the python code to be orange. it is possible?

**Comment by Duvancho321** [comment]
{python py, include=FALSE }

**Comment by Duvancho321** [comment]
I'm sorry, I already know how

decorate_chunk("py") %>% 
  flair_rx(".", color = "orange")

**Comment by kbodwin** [comment]
There is also a `flair_all()` function that does the same thing, perhaps a little more simply. :)
