### ISSUE TITLE
Possible to decorate other languages?

### ISSUE THREAD

**Issue by dmalan** [kbodwin/flair#12]
Might it be feasible to add flair to source code in languages other than R? At the moment, code like

    ```{c example, attr.source='.numberLines', eval=FALSE, include=FALSE}
    while (condition)
    {
        // statements
    }
    ```
    
    ```{r, echo=FALSE}
    library(flair)
    decorate("example") %>%
      flair("condition")
    ```

ends up erring with

```
c374b1014b5be.c:1:1: error: expected identifier or ‘(’ before ‘while’
 while (condition)
 ^~~~~
make: *** [c374b1014b5be.o] Error 1
```

presumably because the decorated C code is being eval'd too. Would definitely be handy to add flair to arbitrary languages or plaintext blocks, even if via simple substring matches or regexes.

Thank you!

**Comment by andrewheiss** [comment]
This is fortunately already possible! You just have to tell `decorate()` to not evaluate the `example` chunk"

````
```{c example, eval=FALSE, include=FALSE}
while (condition)
{
    // statements
}
```

```{r, echo=FALSE}
decorate("example", eval = FALSE) %>%
  flair("condition")
```
````

<img width="360" alt="image" src="https://user-images.githubusercontent.com/73663/81243561-27b66d00-8fde-11ea-92ea-efc266801a63.png">

**Comment by kbodwin** [comment]
I believe PR #10 makes flairing work with any language supported by R Markdown.  Let me know if you encounter any problems with it, please!  I'm not deeply familiar with other languages myself; I only really speak R. :)

**Comment by dmalan** [comment]
Ah, wonderful! Thank you, both!
