### ISSUE TITLE
add pkgdown URL to repo description and to README?

### ISSUE THREAD

**Issue by maelle** [kbodwin/flair#3]
First of all, this is a really awesome package, thanks a ton for making it!

I have two small suggestions regarding the pkgdown URL, could you add it

* to the GitHub repo description i.e. near " decorate your R code"?

* as a warning at the top of the README "if you're reading this on GitHub you won't see the formatting so head to the pkgdown website" or so?

In any case, thanks again for this package!

**Comment by kbodwin** [comment]
Done - good ideas, thank you!

**Comment by ginolhac** [comment]
Hello,
just to let you know that the repo url still points to the old one.
thanks for a fantastic package!
![image](https://user-images.githubusercontent.com/710181/93185113-53402580-f73d-11ea-93b7-4ece7f21deff.png)

**Comment by maelle** [comment]
In case you want to add a redirect, we have some guidance in the dev version of rOpenSci dev guide

https://github.com/ropensci/dev_guide/blob/164e8b5f1918410277444abeb1b0e2c7e8f2eb37/appendix.Rmd#L257
